version = 0.1
[dev.deploy.parameters]
stack_name = "vault"
resolve_s3 = true
s3_prefix = "vault"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "vault"
resolve_s3 = true
s3_prefix = "vault"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
image_repositories = []
